# Generated by Django 2.2 on 2020-01-14 19:04

from django.db import migrations, models
import django.db.models.deletion
import tour_api.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True)),
                ('destination_type', models.CharField(choices=[(tour_api.enums.DestinationTypes('adventure'), 'adventure'), (tour_api.enums.DestinationTypes('cultural'), 'cultural')], max_length=10)),
                ('danger_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('destination', models.ManyToManyField(to='tour_api.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('capacity', models.IntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_api.Package')),
            ],
        ),
    ]
