# Generated by Django 2.2 on 2020-01-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('openweather_id', models.IntegerField()),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.Range')),
            ],
        ),
    ]
